### ISSUE TITLE
Add css to signup page

### ISSUE THREAD

**Issue by nileshkr022** [industrustech/hacktoberfestindus2023#22]
I want to add CSS to index html with relevant pictures for social media links..... can you assign this issue to me with hacktoberfest label.

**Comment by industrustech** [comment]
@nileshkr022 Hi Nilesh, 

Thank you for your interest in contributing! While we appreciate your enthusiasm, this repository is currently excluded from Hacktoberfest 2024 contributions. However, we would love to see your contributions on other repositories that are part of Hacktoberfest. Feel free to check those out and make valuable contributions there!

**Comment by nileshkr022** [comment]
> @nileshkr022 Hi Nilesh, 
> 
> Thank you for your interest in contributing! While we appreciate your enthusiasm, this repository is currently excluded from Hacktoberfest 2024 contributions. However, we would love to see your contributions on other repositories that are part of Hacktoberfest. Feel free to check those out and make valuable contributions there!
> 
> 

Can you mention if you have any
